name: Build Snake for the ESP32 Action
description: Simple Github Action that automatically builds Snake for the ESP32 on push (and on manual execution for debugging). Uses ESP-IDF's own CI action (https://github.com/espressif/esp-idf-ci-action) to build and caches the Ccache directory to reduce build time in subsequent runs.
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Cache Ccache Directory
      uses: actions/cache@v6
      with:
        path: .ccache
        key: ${{ runner.os }}-esp-idf-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-esp-idf-docker-

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32
        path: '.'
        extra_docker_args: >-
          -v ${{ github.workspace }}/.ccache:/root/.ccache
          -e CCACHE_DIR=/root/.ccache