name: Build Snake for the ESP32 Action
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache Ccache Directory
      uses: actions/cache@v4
      with:
        path: .ccache
        key: ${{ runner.os }}-esp-idf-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-esp-idf-docker-

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32
        path: '.'
        extra_docker_args: >-
          -v ${{ github.workspace }}/.ccache:/root/.ccache
          -e CCACHE_DIR=/root/.ccache